<?php
// @codingStandardsIgnoreFile
$form_data = $block->getFormData();
$form_url = $block->getFormUrl();
?>
<div class="fawrygateway-checkout">
	<?php
	if( !$block->getOrderOk() )
	{
		?>
		<p><?php echo $block->getErrorMessage()?></p>
		<div class="actions-toolbar">
			<div class="primary">
				<a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
			</div>
		</div>
	<?php
	} else
	{
	?>
		<p><?php echo __( 'Processing order #%1... Please wait.', $block->escapeHtml( $block->getOrderId() ) ) ?></p>

	<img src="<?php echo $block->getViewFileUrl( 'Tiefanovic_FawryGateway::images/ajax-loader.gif' );?>" /><br/>
	<?php echo __( 'Redirecting...' );?>
		<form id="frm_fawrygateway_redirect" action="<?php echo $form_url?>" method="POST" style="display: none">
			<?php
			foreach ($form_data as $key => $val) {
				echo "<input type='hidden' name='{$key}' value='{$val}' />";
			}
			?>
		</form>
		<script type="text/javascript">
			require([
				'jquery'
			], function(jQuery) {
				jQuery(document).ready(function () {
					jQuery('#frm_fawrygateway_redirect').submit();
				});
			});
		</script>
		<?php
	}
	?>
</div>